version: '3'
services:
  blagues-api:
    container_name: blagues-api
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '3001:3001'
  webpack_dev:
    container_name: webpack_dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: npx webpack --mode development --watch
