name: Format
on:
  pull_request:
    branches: [master]
jobs:
  format:
    name: Jokes Validation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Format
        run: |
          yarn
          yarn format-jokes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting jokes
          branch: ${{ github.head_ref }}
